### ISSUE TITLE
[DT-003] Telegram Nickname

### ISSUE THREAD

**Issue by Vitalii-Kryshtak** [MaximTwister/device-tracker#3]
If user don't have nickname in the telegram account, we have a problem in the telegram listener. Field `nickname` cant be empty.

> " endpoint http://127.0.0.1:8000/collector/api/v1/telegram-account/ response: {'nickname': ['This field may not be null.']} "

**Comment by MaximTwister** [comment]
@Vitalii-Kryshtak Do we have PR for this issue?
